services:
    mongodb:
        image: mongo:latest
        container_name: recog-db
        hostname: database
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    recognition:
        build: ./recognition/
        container_name: recognition-service
        hostname: service
        environment:
            DATABASE_TYPE: mongo
            DATABASE_HOSTNAME: database
            DATABASE_PORT: 27017
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "8080:8080"
    ui:
        build: ./recognition-ui/
        container_name: recognition-ui
        volumes:
            - ./recognition-ui/templates:/etc/nginx/templates
        environment:
            REST_SERVICE_HOSTNAME: service
            REST_SERVICE_PORT: 8080
            NGINX_PORT: 80
        ports:
            - "80:80"
